### ISSUE TITLE
Failted to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by depesr** [jpodwys/cache-service-cache-module#12]
Setting the value of 'cache-module-local-storage' exceeded the quota
cacheModule.js:221

**Comment by jpodwys** [comment]
This is a browser error indicating that the data you're trying to set to localStorage exceeds the browser's available capacity. You can read more about storage limits on [this MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits).

Your options are:
1. Decrease the amount of data you're storing. If you're fetching the data from an API and it's more than you need, update the API. If you cannot update the API, filter the data set down to the smallest amount you need before storing it.
2. Use a different browser storage mechanism such as IndexedDB. I don't recall for certain, but I believe localStorage and IndexedDB have separate quotas, although this may differ by browser.

Please let me know if I misunderstood the issue.

**Comment by depesr** [comment]
From my perspective, the setItem function should be called from inside try section.
Thus if setItem is unable to set new item in localStorage, nothing will happen (no save-ing in localstorage) and the program will continue without any errors, calling API request method.

As for my option:
1. I'm already filtering everything I can
2. It's just translating my problem to another storage. If indexedDB has any quota, I would get same problem just maybe later on.

So in my opinion there are two possibilities:
1. Add internal quota calculation. So I can initialize cache service with eg. 2MB storage. And internally it will check if storage is not full. Once it's full it won't use caching anymore
2. move all `setItem` calls into try catch sections

**Comment by jpodwys** [comment]
As you can see [here](https://github.com/jpodwys/cache-service-cache-module/blob/master/cacheModule.js#L106-L119), `overwriteBrowserStorage ` (called on line 116) is already called from within a try/catch block.

Are you saying that this error causes your app to stop running? Or does it simply print something to the console? I may need additional information such as a screenshot of the console showing the exact error text.

**Comment by jpodwys** [comment]
Are you satisfied with this response?

**Comment by depesr** [comment]
There are several other places where `overwriteBrowserStorage` is not called from within `try`.
Like expire function, self.del etc.
Maybe just try to write as much data to localStorage as you can. Once there are too much data, next set operation will throw exception exactly on line `221`.
That's why I'm trying to convince You to move line 221 up two rows :)

**Comment by jpodwys** [comment]
Ahh, I'm not sure how I missed all the other uses of `overwriteBrowserStorage`, my apologies! I've created a PR (#13) to address the issue. Please take a look, or just try pinning to the branch, and let me know if it addresses the issue for you.

**Comment by depesr** [comment]
Looks fine to me.

Maybe one other question. How about adding third `type` option: `indexedDb`? The thing is, local and session storage are often limited in size, in my case it's like 5MB, which is way to small. Just an idea...

**Comment by jpodwys** [comment]
I've published `2.0.1` to NPM.

I currently have no plans to add `indexedDB` support to this library. If you're feeling adventurous, wrapping [idb-keyval](https://github.com/jakearchibald/idb-keyval) in a new package that match's this one's API seems pretty simple, especially if you don't need `mget`, `mset`, or background refresh.

Sorry, I know that's not the answer you're looking for.

**Comment by depesr** [comment]
I've already done that in a private repo :) I just thought it would be nice to have a multipurpose package.
Anyway thanks, for the fix.
